[project]
name = "lsm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mpi4py>=4.1.1",
    "numpy>=2.3.4",
]

[tool.uv.workspace]
members = [
    "LSM_project_2",
]
